src/components/user-settings/CoursesList.jsx
src/components/visualizacao-cursos/CoursesListVisualization.jsx

- Adicionando botão de download de cursos em CSV

Botão download csv cursos

---

src/components/filter-components/TableSelectCourses.jsx
src/components/user-settings/CoursesList.jsx
src/components/user-settings/FormativeTrailsList.jsx
src/model/courses-model.js
src/model/trilhas-model.js
src/services/course-service.js
src/services/trailsService.js

- Ordenação de cursos nas configurações por data de atualização e criação.

feat: Ordenação de cursos por createdAt e updateAt

---

src/app/App.jsx
src/components/header/HeaderHome.jsx
src/pages/AboutPage.jsx
src/pages/CoursesPage.jsx
src/pages/Denied.jsx
src/pages/FAQ.jsx
src/pages/FaleConosco.jsx
src/pages/ForgetPassword.jsx
src/pages/HistoryPlaforPage.jsx
src/pages/HomePage.jsx
src/pages/Login.jsx
src/pages/NotFound.jsx
src/pages/ResetPassword.jsx
src/pages/SettingsPage.jsx
src/routes/CustomRoutes.jsx

- Nova estrutura de rotas e aumento da segurança de acesso às páginas de cadastro
- Clean Code

Rotas e CleanCode

---

src/components/user-settings/StudyPlanRegister.jsx

- Correção de links de redirecionamento ao adicionar plano

fix: redirect fix

---

src/components/user-settings/ListSearchLogs.jsx
src/components/user-settings/StudyPlanView.jsx
src/helpers/downloadBlob.js
src/model/study-plans-model.js
src/services/study-plans-service.js

- Botão de download dos cursos de um Plano de Estudo em CSV

feat: Download StudyPlan CSV

---

vercel.json

- Configuração de rotas Vercel

feat: Redirecionamento Vercel

---

package.json
src/app/App.jsx
src/model/adm-model.js
src/pages/Login.jsx
src/routes/CustomRoutes.jsx

- Adicionando banner de solicitação de uso de Cookies [LGPD].

Banner de uso de cookies

---

src/routes/CustomRoutes.jsx

- Atualizando informações de segurança Cookie LGPD.

fix: Informações de segurança Cookie LGPD

---

.env.example
src/routes/CustomRoutes.jsx

- Atualizando link de domínio da autorização de uso de cookies, informações de segurança.

fix: Atualizando link de domímio autorização de cookies

---

.env.example
src/routes/CustomRoutes.jsx
src/services/auth-axios.js

- Renomeando variáveis de ambiente

refact: Renomeando variáveis de ambiente

---

.eslintrc.cjs
package-lock.json
package.json
src/components/user-settings/FormativeTrailsRegister.jsx

- Removendo react-sortable-hoc (dependência desatualizada)

refact: Removendo dependencias desatualizadas

---

src/model/adm-model.js
src/model/itineraries-model.js
src/pages/HomePage.jsx
src/services/auth-axios.js

- Tratamento de erro de conexão com servidor

refact: Tratando erro de conexão com servidor

---

src/model/adm-model.js
src/pages/HomePage.jsx

- Condicional nas trilhas aleatórias homepage (tratamento caso não exista)

fix: Condicional Trilhas Aleatórias Homepage

---

src/components/header/HeaderHome.jsx
src/pages/AboutPage.jsx
src/pages/HomePage.jsx

- Mudando vídeo de apresentação para página Sobre
- Mudando layout botão login (base proedu)

fix: Vídeo apresentação e botão login

---

.env.example
src/routes/CustomRoutes.jsx

fix: Enviroment

---

src/components/user-settings/HistoricoItens.jsx
src/components/user-settings/SystemLog.jsx
src/model/adm-model.js
src/pages/SettingsPage.jsx
src/routes/CustomRoutes.jsx

Feita a tela de visualização de cursos / trilhas.

Log de visualização de cursos / trilhas

---

src/components/user-settings/CourseRegister.jsx
src/components/user-settings/EvaluateChanges.jsx
src/components/user-settings/EvaluateChangesPage.jsx
src/components/user-settings/MyProfile.jsx
src/helpers/colorCourseStatus.js
src/model/adm-model.js
src/model/courses-model.js
src/pages/SettingsPage.jsx
src/routes/CustomRoutes.jsx
src/services/auth-axios.js
src/services/course-service.js
src/services/login-service.js

- Adicionando página de análise de cursos pendentes
- Refatorando rotas da aplicação

feat: Página de Análise de Cursos Pendentes

---

index.html
src/components/CourseModalVisualization.jsx
src/components/ScrollToTop.jsx
src/components/filter-components/TableAddTrailStudyPlan.jsx
src/components/filter-components/TableSelectCourses.jsx
src/components/header/HeaderHome.jsx
src/components/user-settings/CatCompRegister.jsx
src/components/user-settings/CategCompList.jsx
src/components/user-settings/CompList.jsx
src/components/user-settings/CompRegister.jsx
src/components/user-settings/CourseRegister.jsx
src/components/user-settings/CoursesList.jsx
src/components/user-settings/FormativeTrailsList.jsx
src/components/user-settings/FormativeTrailsRegister.jsx
src/components/user-settings/InstitutionRegister.jsx
src/components/user-settings/InstitutionsList.jsx
src/components/user-settings/StudyPlanRegister.jsx
src/components/user-settings/StudyPlanView.jsx
src/components/user-settings/SubtemaRegister.jsx
src/components/user-settings/SubtemasList.jsx
src/components/user-settings/TemasList.jsx
src/components/user-settings/TemasRegister.jsx
src/helpers/reformuladorDeElementosCytoscape.js
src/pages/FAQ.jsx
src/pages/FaleConosco.jsx
src/pages/HomePage.jsx
src/pages/SettingsPage.jsx
src/routes/CustomRoutes.jsx
src/schemas/registers/registersSchema.js

- URL /suporte no Fale Conosco
- Posicionamentos das acessibilidade e visualização dos equivalentes
- Status das entidades refatoradas
- Link para os planos de estudo no Header
- Páginas de edição e visualização das entidades de dados refatoradas com o novo status das entidades

Equivalentes

---

src/pages/HomePage.jsx

Correção na exibição de cursos e trilhas formativas da tela inicial (não estava implementado)

hotfix: visualizar cursos e trilha homepage

---

src/components/documents/DocumentsVisualization.jsx
src/components/documents/ViewAllDocumentsModal.jsx
src/components/user-settings/DocumentRegister.jsx
src/components/user-settings/DocumentsList.jsx
src/components/user-settings/EvaluateChanges.jsx
src/components/user-settings/StudyPlans.jsx
src/components/user-settings/UsersList.jsx
src/model/adm-model.js
src/model/documents-model.js
src/model/index.js
src/pages/HistoryPlaforPage.jsx
src/pages/SettingsPage.jsx
src/routes/CustomRoutes.jsx
src/schemas/registers/registersSchema.js
src/services/documents-service.js
src/services/index.js

- Visualização e edição de documentos

feat: Visualização e edição de documentos

---

src/components/filter-components/TableSelectCourses.jsx
src/pages/HomePage.jsx
src/pages/homepage.css

- Corrigindo bug ao abrir modal de adicionar cursos equivalentes

hotfix: Corrigindo modal adicionar equivalentes

---

src/components/footer/FooterGov.jsx
src/components/privacyTerms/TermPrivacyModal.jsx

- Adicionando link para política de privacidade no footer

feat: Link política de privacidade no footer

---

src/pages/AboutPage.jsx
src/pages/AboutPage.module.css
src/pages/HistoryPlaforPage.jsx

layout: Ajustando layout sobre e historico

---

src/components/user-settings/DocumentRegister.jsx
src/components/user-settings/DocumentsList.jsx
src/pages/FaleConosco.jsx

layout: Novo Layout Fale Conosco

---

src/components/privacyTerms/TermConsentLogin.jsx
src/components/user-settings/StudyPlanView.jsx
src/components/user-settings/StudyPlans.jsx
src/model/adm-model.js
src/model/study-plans-model.js
src/pages/Login.jsx
src/routes/CustomRoutes.jsx
src/services/study-plans-service.js
src/services/users-service.js

- Progresso no plano de estudo
- Termo de consentimento no login

feat: Progresso no plano de estudo

---

src/components/user-settings/CategCompList.jsx
src/components/user-settings/CompList.jsx
src/components/user-settings/CoursesList.jsx
src/components/user-settings/DocumentsList.jsx
src/components/user-settings/FormativeTrailsList.jsx
src/components/user-settings/FormativeTrailsRegister.jsx
src/components/user-settings/InstitutionsList.jsx
src/components/user-settings/StudyPlanView.jsx
src/components/user-settings/StudyPlans.jsx
src/components/user-settings/SubtemasList.jsx
src/components/user-settings/TemasList.jsx
src/pages/Denied.jsx
src/pages/HistoryPlaforPage.jsx
src/pages/Login.jsx
src/pages/SettingsPage.jsx
src/routes/CustomRoutes.jsx
src/schemas/registers/updatePasswordSchema.js

- Corrigindo loading infinito ao tentar autenticar sem aceitar uso de cookies

fix: Loading infinito ao entrar sem aceitar uso de cookies
